version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=   "USUARIO DO BANCO"
      - POSTGRES_PASSWORD=  "SENHA DO BANCO"
      - POSTGRES_DB= "NOME DO BANCO"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5422:5432'

volumes:
  postgres: