version: '3.8'
services:
  app:
    container_name: api
    build: .
    command: npm run dev
    volumes: 
      - .:/usr/src/app
    ports:
      - "4444:4444"
   
  db:
    container_name: banco_de_dados
    image: postgres:latest
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB}
    ports:
      - '5422:5432'

volumes:
  postgres:

