version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=`${USER}`
      - POSTGRES_PASSWORD=`${PASSWORD}`
      - POSTGRES_DB=$`{DB1}`
    ports:
      - '5422:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - iclinica-net
  app-1:
    build: .
    command: npm run dev
    volumes: 
      - .:/usr/src/app
    ports:
      - "4444:4444"
    depends_on:
      - db
    networks:
      - iclinica-net

volumes:
  postgres:
networks:
    iclinica-net: