version: '3.8'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/node_modules/bcrypt/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:10.20
    restart: always
    environment:
      - POSTGRES_USER = "USUARIO DO BANCO"
      - POSTGRES_PASSWORD = "SENHA DO BANCO"
      - POSTGRES_DB = "NOME DO BANCO"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5422:5432'

volumes:
  postgres: